### ISSUE TITLE
Does this work with home-manager?

### ISSUE THREAD

**Issue by evalexpr** [yaxitech/ragenix#136]
I want to use this over `agenix` but it looks like [we don't pass through the `homeManagerModules` from agenix](https://github.com/yaxitech/ragenix/blob/main/flake.nix#L368), is there something I'm missing?

**Comment by tunamelon** [comment]
> I want to use this over `agenix` but it looks like [we don't pass through the `homeManagerModules` from agenix](https://github.com/yaxitech/ragenix/blob/main/flake.nix#L368), is there something I'm missing?

Just wondering is this the case? It’d be great to use ragenix but I’d need a full drop in replacement for agenix on Darwin, NixOS, and home-manager especially for non NixOS Linux.
