### ISSUE TITLE
recursive-nix needed for simple install

### ISSUE THREAD

**Issue by sweenu** [yaxitech/ragenix#65]
In the README we get the impression that the `recursive-nix` feature is only needed if we want to contribute but for me, simply putting ragenix as an input in my flake.nix and having it as a command in my devshell gives me:
```
error: a 'x86_64-linux' with features {recursive-nix} is required to build '/nix/store/dn03sf91527lndd0mj6s35qsd6v38a3b-ragenix.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test}
```

Is `recursive-nix` needed to just use ragenix? In that case maybe it should be listed as a dependency or something.

**Comment by veehaitch** [comment]
Thanks for reporting. `recursive-nix` shouldn't be required to merely build `ragenix`. Probably #62 messed something up. Cc. @blaggacao

**Comment by blaggacao** [comment]
Thanks for taking care of this. i _thought_ I had taken care, but seems like I aimed quite short at the wrong code path.
